---
abstract: 'plugin for Data::Compare to handle Set::Object objects'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
  version: 0.77
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Compare-Plugins-Set-Object
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::Compare: 0.06
  English: 0
  List::Util: 0
  Set::Object: 0
  perl: 5.8.0
resources:
  bugtracker: http://github.com/mjg/Data-Compare-Plugins-Set-Object/issues
  homepage: http://github.com/mjg/Data-Compare-Plugins-Set-Object/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/mjg/Data-Compare-Plugins-Set-Object.git
version: 1.000000
